version: '3'

services:
  site:
    image: potdig/poshi-layout
    build:
      context: .
    volumes:
      - ./src:/work/src
    ports:
      - 0.0.0.0:3000:3000
      - 0.0.0.0:16834:16834
    restart: always
